apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/created-by: kim-snatch
    app.kubernetes.io/part-of: kim-snatch
    app.kubernetes.io/managed-by: kustomize
  name: kyma
  namespace: system
spec:
  commonName: snatch-webhook-service.kyma-system
  dnsNames:
  - kim-snatch-webhook-service.kyma-system.svc
  - kim-snatch-webhook-service.kyma-system.svc.cluster.local
  isCA: true
  issuerRef:
    name: kyma
    namespace: system
  secretRef:
    name: snatch-certificates
    namespace: system
