apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/created-by: kim-snatch
    app.kubernetes.io/part-of: kim-snatch
    app.kubernetes.io/managed-by: kustomize
  name: kyma  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: kyma-system
spec:
  dnsNames:
  - kim-snatch-webhook-service.kyma-system.svc
  - kim-snatch-webhook-service.kyma-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kyma
  secretName: kim-snatch-certificates # this secret will not be prefixed, since it's not managed by kustomize

