name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: run-linter
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.23.4'

      - name: Run linter
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
        with:
          version: v1.61.0
